language: python
python:
  - "3.6"
  

#safe_list
#will be added
# branches:
#   only:
#   - master
#   - /^(?i:sprint)_.*$/

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run spot test --all
